name: Publish to PyPI (manually)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (Like v0.1.3)"
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: |
          pip install --upgrade pip
          pip install build hatchling hatch-vcs

      - name: Create version tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
